service: trustana-cms-api
frameworkVersion: ">=3"

plugins:
  - serverless-esbuild

provider:
  name: aws
  region: ap-southeast-1
  stage: prod
  runtime: nodejs18.x
  architecture: arm64
  memorySize: 512
  timeout: 15
  logs:
    httpApi: true
  environment:
    NODE_OPTIONS: "--enable-source-maps"
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    DATABASE_URL: ${ssm:/trustana-cms/prod/DATABASE_URL}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:GetParameters
          Resource:
            - arn:aws:ssm:ap-southeast-1:${aws:accountId}:parameter/trustana-cms/prod/*
        - Effect: Allow
          Action: kms:Decrypt
          Resource: "*"
          Condition:
            StringEquals:
              kms:ViaService: ssm.ap-southeast-1.amazonaws.com

functions:
  api:
    name: trustana-cms-api-prod
    handler: src/lambda.handler
    events:
      - httpApi:
          method: ANY
          path: /
      - httpApi:
          method: ANY
          path: /{proxy+}

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    keepNames: true
    platform: node
    target: node18
    exclude:
      - aws-sdk
    external:
      - "@prisma/client"
      - "@nestjs/microservices"
      - "@nestjs/websockets"
      - "@nestjs/websockets/socket-module"
      - "@nestjs/microservices/microservices-module"
      - "class-transformer/storage"     
      - "swagger-ui-express"
      - "swagger-ui-dist"  

package:
  patterns:
    - node_modules/@prisma/client/**
    - node_modules/.prisma/**
    - node_modules/swagger-ui-dist/** 
    - prisma/**
    - "!**/*.spec.*"
    - "!**/*.test.*"
    - "!src/**"
    - "!.git/**"
    - "!.github/**"
