service: trustana-cms-api
frameworkVersion: ">=3"

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs18.x
  architecture: arm64
  memorySize: 512
  timeout: 15
  environment:
    NODE_OPTIONS: "--enable-source-maps"

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: ANY
          path: /
      - httpApi:
          method: ANY
          path: /{proxy+}

package:
  patterns:
    - dist/**
    - node_modules/**
    - package.json
    - package-lock.json
    - prisma/**
    - "!**/*.spec.*"
    - "!.git/**"
    - "!.github/**"
