name: Deploy Backend API with Serverless

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1
  NODE_VERSION: "18"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install
        run: npm ci

      - name: Generate Prisma client
        if: hashFiles('prisma/schema.prisma') != ''
        run: npx prisma generate

      - name: Build
        run: npm run build

      - name: Prune dev deps
        run: npm prune --production

      - name: Install Serverless CLI
        run: npm i -g serverless

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: gha-serverless-deploy

      - name: Deploy
        run: serverless deploy --stage prod

      - name: Show endpoints
        run: serverless info --verbose
