name: Deploy Backend CMS API app with Serverless

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1
  NODE_VERSION: "18"
  SLS_TELEMETRY_DISABLED: "1"

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-prod
      cancel-in-progress: false

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install
        run: npm ci

      - name: Generate Prisma client
        if: hashFiles('prisma/schema.prisma') != ''
        run: npx prisma generate

      # Run migrations before build/deploy
      - name: Prisma migrate status
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate status

      - name: Prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy

      # optional build if you still compile for local runs
      - name: Build
        run: npm run build || echo "skip build"

      - name: Assert AWS role secret present
        env:
          AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        run: |
          if [ -z "$AWS_ROLE_TO_ASSUME" ]; then
            echo "AWS_ROLE_TO_ASSUME is not set. If it's an Environment secret, set 'environment:' on this job."
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: gha-serverless-deploy
          audience: sts.amazonaws.com

      - name: Show Serverless version and plugins
        run: |
          npx -y serverless@3 --version
          npx -y serverless@3 plugin list

      - name: Deploy
        run: npx -y serverless@3 deploy --stage prod

      - name: Show endpoints
        run: npx -y serverless@3 info --verbose
